export default {
    LOGIN: "Login",
    SIGNUP: "Signup",
    INITIALSCREEN: "InitialScreen",
    HOME: "Home",
    SEARCH: "Search",
    PROFILE: "Profile",
    CREATEPOST: "CreatePost",
    NOTIFICATION: "Notification",
    PROFILE: "Profile",
    TABROUTES: "TabRoutes",
    OTP_VERIFICATION: "OtpVerification",
    WEB_VIEW: "Webview",
    PROFILE_EDIT:"ProfileEdit",
    LINKS:"Links",
    ADD_POST:"AddPost",
    POST_DETAIL:"PostDetail",
    CHATS:"Chats",
    MESSAGES:"Messages"
}